### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.report'

### ISSUE THREAD

**Issue by thisislola** [abrignoni/ALEAPP#311]
I have the same issue as https://github.com/abrignoni/ALEAPP/issues/119

On a mac M1:

```
$ pip3 list

...
report             0.0.1
reports            0.4.1
```

When I run: 

```
astra@centralop RLEAPP-main % **python3 rleappGUI.py** 
Traceback (most recent call last):
  File "/Users/astra/Desktop/TOOLS/RLEAPP-main/rleappGUI.py", line 4, in <module>
    import rleapp
  File "/Users/astra/Desktop/TOOLS/RLEAPP-main/rleapp.py", line 6, in <module>
    **import scripts.report as report
ModuleNotFoundError: No module named 'scripts.report'**
astra@centralop RLEAPP-main % 
```

I cannot find another module that could be the issue. I can run ALEAPP without issues. 
I have uninstall and installed again report with pip3.

**Comment by thisislola** [comment]
Thank you for the quick reply! I have tried downloading it as a zip and using the native mac tool to unzip it and also downloading it with git. Same issue. Might be on my end then.
