### ISSUE TITLE
google.protobuf error

### ISSUE THREAD

**Issue by hyuunnn** [abrignoni/ALEAPP#79]
```
(test) D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master>python aleappGUI.py
Traceback (most recent call last):
  File "aleappGUI.py", line 1, in <module>
    import aleapp
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\aleapp.py", line 9, in <module>
    from scripts.ilap_artifacts import *
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\scripts\ilap_artifacts.py", line 53, in <module>
    from scripts.artifacts.usagestats import get_usagestats
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\scripts\artifacts\usagestats.py", line 4, in <module>
    import scripts.artifacts.usagestats_pb.usagestatsservice_pb2 as usagestatsservice_pb2
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\scripts\artifacts\usagestats_pb\usagestatsservice_pb2.py", line 14, in <module>
    from . import configuration_pb2 as configuration__pb2
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\scripts\artifacts\usagestats_pb\configuration_pb2.py", line 14, in <module>
    from . import window_configuration_pb2 as window__configuration__pb2
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\scripts\artifacts\usagestats_pb\window_configuration_pb2.py", line 14, in <module>
    from . import rect_pb2 as rect__pb2
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\scripts\artifacts\usagestats_pb\rect_pb2.py", line 14, in <module>
    from . import privacy_pb2 as privacy__pb2
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\scripts\artifacts\usagestats_pb\privacy_pb2.py", line 15, in <module>
    from . import descriptor_pb2  as descriptor__pb2
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\scripts\artifacts\usagestats_pb\descriptor_pb2.py", line 2010, in <module>
    'Location' : _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\test\test\lib\site-packages\google\protobuf\internal\python_message.py", line 189, in __init__
    _AttachFieldHelpers(cls, field)
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\test\test\lib\site-packages\google\protobuf\internal\python_message.py", line 295, in _AttachFieldHelpers
    field_descriptor.GetOptions().packed)
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\test\test\lib\site-packages\google\protobuf\descriptor.py", line 147, in GetOptions
    from google.protobuf import descriptor_pb2
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\test\test\lib\site-packages\google\protobuf\descriptor_pb2.py", line 112, in <module>
    _sym_db.RegisterEnumDescriptor(_FIELDDESCRIPTORPROTO_TYPE)
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\test\test\lib\site-packages\google\protobuf\symbol_database.py", line 107, in RegisterEnumDescriptor
    self.pool._AddEnumDescriptor(enum_descriptor)
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\test\test\lib\site-packages\google\protobuf\descriptor_pool.py", line 263, in _AddEnumDescriptor
    self._CheckConflictRegister(enum_desc, enum_desc.full_name, file_name)
  File "D:\Forensic_Challenge\digitalcorpora-Android 10\ALEAPP-master\test\test\lib\site-packages\google\protobuf\descriptor_pool.py", line 191, in _CheckConflictRegister
    raise TypeError(error_msg)
TypeError: Conflict register for file "google/protobuf/descriptor.proto": google.protobuf.FieldDescriptorProto.Type is already defined in file "descriptor.proto". Please fix the conflict by adding package name on the proto file, or use different name for the duplication.
```

**Comment by abrignoni** [comment]
Got 3 emails stating this is an issue. Going to look into it.
Thoughts @ydkhatri?

**Comment by ydkhatri** [comment]
Seems to be a rehash of the one we had earlier (last year). There are problems with google's protobuf. It does not perform the same way on every platform and every version of python. I recall the last time we had narrowed this down to a specific version of protobuf (on one particular platform) that did not work. Seems we need to do that again. 
Can you ask whoever emailed you to provide-
* the version of protobuf installed
* version of python installed
* platform (os)

**Comment by abrignoni** [comment]
Doing so now.

**Comment by hyuunnn** [comment]
Python 3.9 (32bit, 64bit)
Windows 10 (Version 2004) @ydkhatri 
![image](https://user-images.githubusercontent.com/15611739/101844570-1050eb00-3b90-11eb-8955-f12d8ccd0dcc.png)
![image](https://user-images.githubusercontent.com/15611739/101844625-36768b00-3b90-11eb-8eac-5716c7fc42f8.png)

**Comment by ydkhatri** [comment]
> Python 3.9 (32bit, 64bit)
> Windows 10 (Version 2004) @ydkhatri
> It works normally in 3.8.
> 

I get the same with python 3.9. Works with earlier version (3.7, 3.8). For now, **just avoid python 3.9**

**Comment by ydkhatri** [comment]
OK, this seems to fix it for python 3.9 (and protobuf 3.14.0) on windows 10.

In file `\scripts\artifacts\usagestats_pb\privacy_pb2.py`

Change
`from . import descriptor_pb2  as descriptor__pb2`
to
`from google.protobuf import descriptor_pb2  as descriptor__pb2`

Please run it and see if it parses usagestats. I will later test with older versions and see if that works too.

**Comment by hyuunnn** [comment]
![image](https://user-images.githubusercontent.com/15611739/101849694-958dcd00-3b9b-11eb-9ef5-b31797047d72.png)
nice :) @ydkhatri

**Comment by digitalsleuth** [comment]
Good evening!
I hate to be the bearer of bad news, but I'm afraid this issue extends beyond Python 3.9, so I'd like to see if we can re-open the issue.
When installing aleapp on a barebones installation of Ubuntu 20.04 (which comes with Python 3.8 by default), I get the following:
```
root@09ce0a2b6800:/aleapp# python3 aleapp.py
Traceback (most recent call last):
  File "aleapp.py", line 9, in <module>
    from scripts.ilap_artifacts import *
  File "/aleapp/scripts/ilap_artifacts.py", line 53, in <module>
    from scripts.artifacts.usagestats import get_usagestats
  File "/aleapp/scripts/artifacts/usagestats.py", line 4, in <module>
    import scripts.artifacts.usagestats_pb.usagestatsservice_pb2 as usagestatsservice_pb2
  File "/aleapp/scripts/artifacts/usagestats_pb/usagestatsservice_pb2.py", line 14, in <module>
    from . import configuration_pb2 as configuration__pb2
  File "/aleapp/scripts/artifacts/usagestats_pb/configuration_pb2.py", line 14, in <module>
    from . import window_configuration_pb2 as window__configuration__pb2
  File "/aleapp/scripts/artifacts/usagestats_pb/window_configuration_pb2.py", line 14, in <module>
    from . import rect_pb2 as rect__pb2
  File "/aleapp/scripts/artifacts/usagestats_pb/rect_pb2.py", line 14, in <module>
    from . import privacy_pb2 as privacy__pb2
  File "/aleapp/scripts/artifacts/usagestats_pb/privacy_pb2.py", line 17, in <module>
    from . import descriptor_pb2  as descriptor__pb2
  File "/aleapp/scripts/artifacts/usagestats_pb/descriptor_pb2.py", line 2010, in <module>
    'Location' : _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 189, in __init__
    _AttachFieldHelpers(cls, field)
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 295, in _AttachFieldHelpers
    field_descriptor.GetOptions().packed)
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 147, in GetOptions
    from google.protobuf import descriptor_pb2
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor_pb2.py", line 112, in <module>
    _sym_db.RegisterEnumDescriptor(_FIELDDESCRIPTORPROTO_TYPE)
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/symbol_database.py", line 107, in RegisterEnumDescriptor
    self.pool._AddEnumDescriptor(enum_descriptor)
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor_pool.py", line 263, in _AddEnumDescriptor
    self._CheckConflictRegister(enum_desc, enum_desc.full_name, file_name)
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor_pool.py", line 191, in _CheckConflictRegister
    raise TypeError(error_msg)
TypeError: Conflict register for file "google/protobuf/descriptor.proto": google.protobuf.FieldDescriptorProto.Type is already defined in file "descriptor.proto". Please fix the conflict by adding package name on the proto file, or use different name for the duplication.
```
```
root@09ce0a2b6800:/aleapp# python3 -V
Python 3.8.5
```
Means to duplicate:
```
apt install git -y
git clone https://github.com/abrignoni/aleapp
cd aleapp/
pip3 install -r requirements.txt 
python3 aleapp.py
```
Since this actually works for python3.8.5 as well, any chance you can fix this so it covers this version?

**Comment by ydkhatri** [comment]
> When installing aleapp on a barebones installation of Ubuntu 20.04 (which comes with Python 3.8 by default), I get the following:

You are correct, just tested with linux and macOS (neither works with 3.8), but work with 3.9 now! I believe that one line `if` statement I added needs more fine-tuned logic. Need to test py 3.7, 3.8, 3.9 across Win/Linux/macOS and tweak it to make the right choice.

**Comment by ydkhatri** [comment]
@digitalsleuth , try now. I changed the code, and tested that it works on ubuntu 3.8 and 3.9.

**Comment by ydkhatri** [comment]
Closing, as it seems to be resolved.

**Comment by abrignoni** [comment]
Thank you so much. Been working with folks over email. It is working now.
